### ISSUE TITLE
Compilation error on MacOS on 'Your First App'.

### ISSUE THREAD

**Issue by cmroanirgo** [fyne-io/fyne#2559]
### Describe the bug:
I'm getting a compilation error on MacOS when trying to run the 'Your First App' tutorial (https://developer.fyne.io/started/firstapp.html). The Cmd Line is reporting:

```
# fyne.io/fyne/v2/app
app_darwin.m:3:9: fatal error: 'UserNotifications/UserNotifications.h' file not found

```

Unfortunately, I'm n00b to the language and can't find a way to get better info on where the .h file is expected to be, nor what command line options could be used to show more info.

I'm aware that my OS  (High Sierra) and XCode (10.1) are a bit 'long in the tooth', but would prefer to keep them. I didn't find any documentation on minimum versions, other than a minimum of Go v1.12.

### To Reproduce:
Steps to reproduce the behaviour:
1. Follow the steps in "Getting Started" (Download Go, run `xcode-select --install`, run `go get fyne.io/fyne/v2`)
2. Save the code as displayed on "Your First App" (see above link).
3. try various ways to build or run the app, they all end in the same error message as noted above.

### Device (please complete the following information):
 - **OS:** MacOS (Intel)
 - **Version:** 10.13.6 (High Sierra)
 - **Go version:** go version go1.17.2 darwin/amd64
 - **Fyne version:** v2.1.0
- **XCode version:** Version 10.1 (10B61)

This is the output of `gcc -version`:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

**Comment by nullst** [comment]
> app_darwin.m:3:9: fatal error: 'UserNotifications/UserNotifications.h' file not found

Fyne 2.1 uses the UserNotification framework, which I think was introduced in Mac OS 10.14, so the current version of fyne won't work on 10.13 as is. I have the same problem since I use 10.12 Sierra. See #2478 for details and a workaround (if you modify three files in fyne's code manually, everything works without any problems).

**Comment by cmroanirgo** [comment]
A bit of belated feedback.

The referenced #2478 suggested using v2.0.4 instead. It worked in my instance and have been able to proceed. So, thanks for that!

**Comment by andydotxyz** [comment]
In `v2.1.2`(not yet released) there is a new "legacy" flag that can be used to support older OS like this.
You can test using the head of `release/v2.1.x` branch

**Comment by HDHChris** [comment]
> A bit of belated feedback.
> 
> The referenced #2478 suggested using v2.0.4 instead. It worked in my instance and have been able to proceed. So, thanks for that!

Thanks,I do like this and solve it! greate!

**Comment by HDHChris** [comment]
I hope this compatibility problem can be fixed as soon as possible in the latest version or a more friendly solution prompt can be given!

**Comment by Jacalz** [comment]
@HDHChris This issue has already been resolved in a prior bug fix release of 2.1.x (2.1.2, I think). You should be able compile using `-tags legacy` when you build your application.
