### ISSUE TITLE
Missing xdg-shell-client-protocol.h on fedora with fyne v2.8.0

### ISSUE THREAD

**Issue by heathcliff26** [fyne-io/fyne#6409]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When updating my project from fyne 2.7.4 to 2.8.0, it no longer compiles with the following error:
```
$ fyne build
# github.com/go-gl/glfw/v3.4/glfw
In file included from vendor/github.com/go-gl/glfw/v3.4/glfw/c_glfw_lin_wayland.go:7:
./glfw/src/wl_init.c:44:10: fatal error: xdg-shell-client-protocol.h: No such file or directory
   44 | #include "xdg-shell-client-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1
make: *** [Makefile:24: build] Fehler 1
```

### How to reproduce

1. Install dependencies from [quickstart](https://docs.fyne.io/started/quick/): `sudo dnf install golang golang-misc gcc libXcursor-devel libXrandr-devel mesa-libGL-devel libXi-devel libXinerama-devel libXxf86vm-devel libxkbcommon-devel wayland-devel`
2. Upgrade project to fyne 2.8.0
3. Compile

### Example code

```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
)

func main() {
	a := app.NewWithID("testapp")
	w := a.NewWindow("Test App")
	w.Resize(fyne.NewSize(800, 600))

	w.ShowAndRun()
}
```

### Fyne version

2.8.0

### Go compiler version

go version go1.26.5-X:nodwarf5 linux/amd64

### Operating system and version

Fedora 44

**Comment by andydotxyz** [comment]
The quick start doc was not updated yesterday to match the new requirement, sorry - fixed now (you also need libwayland-dev).

**Comment by heathcliff26** [comment]
`libwayland-dev` looks like a debian package, it does not exist under fedora. I guess the equivalent would be `wayland-devel`, which was already installed on my system for other frameworks.
The current quickstart from fedora for me is:
```
sudo dnf install golang golang-misc gcc libXcursor-devel libXrandr-devel mesa-libGL-devel libXi-devel libXinerama-devel libXxf86vm-devel libxkbcommon-devel wayland-devel
```
Running that command does not install any new packages for me, so it might just be that this header file is not included in fedora or split into a separate package?

Could you please re-open the issue @andydotxyz ?

**Comment by andydotxyz** [comment]
Can you try installing wayland-protocols-devel?

**Comment by heathcliff26** [comment]
Yes, it makes no difference.

**Comment by heathcliff26** [comment]
Huh according to AI, the header is not provided by a package but rather instead supposed to be auto-generated:
```
wayland-scanner client-header \
  /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
  xdg-shell-client-protocol.h
```
That command does indeed generate a header file for me.
Copying it to `/usr/include` does change the error for me to the next missing header file:
```
$ fyne build
# github.com/go-gl/glfw/v3.4/glfw
In file included from vendor/github.com/go-gl/glfw/v3.4/glfw/c_glfw_lin_wayland.go:7:
./glfw/src/wl_init.c:45:10: fatal error: xdg-decoration-unstable-v1-client-protocol.h: No such file or directory
   45 | #include "xdg-decoration-unstable-v1-client-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1
make: *** [Makefile:24: build] Fehler 1
```
Though these files should either be generated by the fyne command, or not included.

**Comment by heathcliff26** [comment]
This looks like it is likely a problem with glfw not generating and shipping the files for v3.4. I found an old PR: https://github.com/go-gl/glfw/pull/283

**Comment by andydotxyz** [comment]
Where is your wayland-scanner binary, is it in the path?

**Comment by heathcliff26** [comment]
Yes it is in the PATH:
```
$ which wayland-scanner 
/usr/bin/wayland-scanner
```

**Comment by andydotxyz** [comment]
Hmm, if it's not that then generations won't be failing (though the default should be in the repo already).

The file should be included internally to the build so you're right it's not a missing file - but instead somehow the build process itself is not finding a local file... Do you have any tags set? or custom CFLAG or LDFLAG for CGO?

**Comment by heathcliff26** [comment]
Looking at glfw it seems for 3.4 the default is not in the repo? At least i can't find it.
And i have not set any additionall flags, just plain `fyne build`

**Comment by andydotxyz** [comment]
It's in my dep chain as far as I can see. If you vendor all the dependencies then what wayland headers do you find in the structure?

**Comment by heathcliff26** [comment]
None as far as i can see. The glfw 3.3 headers are removed and no wayland related headers are added in glfw 3.4.
Here is the commit created by renovate:
https://github.com/heathcliff26/cultures-trainer/commit/171ffcc5db87bdb03931dd65efe4094e4e21d5d5

**Comment by LEX0RE** [comment]
Same thing happen for me, was working in 2.7.4, but when trying to update to 2.8.0, pipeline failed. I've try added the  libwayland-dev, libxkbcommon-dev and wayland-protocols packages, but it still not working : https://github.com/LEX0RE/rockpload/pull/100

As it is on GitHub CI, it's on Ubuntu, but the same error seems to happen

**Comment by andydotxyz** [comment]
Aha! it is a GLFW vendor issue. If you remove the vendor directory the build will work. Of course that is not a solution - but it might help in the short term.

Let's see if we can work with upstream to get this resolved.

I have opened https://github.com/go-gl/glfw/issues/422 - I had hoped it was a simple fix like previous vendor issues but in this case the header lookup seems to have changed so I am not sure on the solution yet.

**Comment by heathcliff26** [comment]
Thank you for looking into it @andydotxyz.

Yes removing the vendor folder does solve it, but it does mean you get problems later when building RPMs/Flatpaks since they always prefer no internet access during build.

**Comment by andydotxyz** [comment]
Upstream fix is https://github.com/go-gl/glfw/pull/423 but I made a temporary workaround here just in case

**Comment by heathcliff26** [comment]
I tried bot the temporary and the upstream fix, however it seems to not work in my project. Here is my diff:
```
$ git diff
diff --git a/vendor/fyne.io/fyne/v2/internal/driver/glfw/wayland_vendor_fix.go b/vendor/fyne.io/fyne/v2/internal/driver/glfw/wayland_vendor_fix.go
new file mode 100644
index 0000000..52986b0
--- /dev/null
+++ b/vendor/fyne.io/fyne/v2/internal/driver/glfw/wayland_vendor_fix.go
@@ -0,0 +1,5 @@
+//go:build required
+
+package glfw
+
+import _ "github.com/go-gl/glfw/v3.4/glfw/glfw/include"
diff --git a/vendor/github.com/go-gl/glfw/v3.4/glfw/build_cgo_hack.go b/vendor/github.com/go-gl/glfw/v3.4/glfw/build_cgo_hack.go
index 7d48dd2..700a528 100644
--- a/vendor/github.com/go-gl/glfw/v3.4/glfw/build_cgo_hack.go
+++ b/vendor/github.com/go-gl/glfw/v3.4/glfw/build_cgo_hack.go
@@ -14,6 +14,7 @@ package glfw
 import (
        // Prevent go tooling from stripping out the c source files.
        _ "github.com/go-gl/glfw/v3.4/glfw/glfw/deps"
+       _ "github.com/go-gl/glfw/v3.4/glfw/glfw/include"
        _ "github.com/go-gl/glfw/v3.4/glfw/glfw/include/GLFW"
        _ "github.com/go-gl/glfw/v3.4/glfw/glfw/src"
 )
```
I have just run `fyne build`, is there something else i'm missing?

**Comment by andydotxyz** [comment]
Those two files do the same thing are you sure you remembered to run "go mod vendor" with the PR applied before building?

**Comment by heathcliff26** [comment]
The 2.8 fyne was already vendored, i just applied the changes manually to each fyne and glfw in the vendor folder, since that seemed easier than to figure out how to pull the PR and should work the same.

**Comment by andydotxyz** [comment]
Can be more specific then on what did not work? I'm a bit confused.
Thanks.

**Comment by heathcliff26** [comment]
Okay, so i have already a project with a branch updated to fyne 2.8 and vendored dependencies.
Than i did:
1. Create file `vendor/fyne.io/fyne/v2/internal/driver/glfw/wayland_vendor_fix.go` with the content from https://github.com/fyne-io/fyne/pull/6434
2. Run `fyne build` <- Still produces the same error
3. Edit `vendor/github.com/go-gl/glfw/v3.4/glfw/build_cgo_hack.go` with the changes from https://github.com/go-gl/glfw/pull/423
4. Repeat 2 <- Still the error

**Comment by andydotxyz** [comment]
I suspect you are hitting build caches, because after I saw it failed for you I tested again before and after this PR and it definitely fixes it here.
Now that it is landed try using @develop as a dependency version and then vendoring, should fix things.

**Comment by heathcliff26** [comment]
You are right, updating fyne in go.mod to
```
fyne.io/fyne/v2 v2.8.1-0.20260724134512-ea9f99dff60c
```
followed by
```bash
go mod tidy
go mod vendor
fyne build
```
works.

Thank you for your work on this issue.
